### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by kms0219kms** [dply-app/dply-app-closed#1]
- [ ] 환불 안내 페이지
- [ ] loading.html, hidden.html 접근 차단
- [ ] 푸시 안된 파일들 푸시하기
